services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    env_file: .env
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: ./app/poetry.lock
        - action: rebuild
          path: ./app/Dockerfile

networks:
  docker1:
    external: true
